friendzone/urls.py
from django.contrib import admin
from django.urls import path,include
from project import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.frontpage,name='front'),
    path('project/',include('project.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from project import views

app_name = 'project'


urlpatterns = [
    path('dashboard/',views.dashboard,name='dash'),
    path('about/',views.about,name='abo'),
    path('album/',views.album,name='alb'),
    path('contact/',views.contact,name='con'),
    path('s_account/',views.settings_account,name='account'),
    path('s_basicinfo/',views.settings_basicinfo,name='basic'),
    path('s_education/',views.settings_education,name='education'),
    path('s_interest/',views.settings_interests,name='interest'),
    path('s_password/',views.settings_password,name='password'),
    path('timeline/',views.timeline,name='time'),
    path('uslogin/',views.uslogin,name='login'),
    path('uslogout/',views.uslogout,name='logout'),
    path('find_friend/',views.find_friend,name='find_friend'),
    path('friends/',views.friends,name='friends'),
    # path('mypost/',views.mypost,name='mypost'),
]
    

templates/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About</title>
    <link rel="shortcut icon" href="{% static 'images/friendzone2.png' %}">
    <script src="{% static 'jquery.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" >
    <style>
        .logo{
            border-radius:50%; 
            height:30px; 
            font-size: 25px;
        }
        .back{
            background: url("/media/{{profile.cover_pic}}");
            height:400px; 
            padding-top: 300px; 
            background-size:cover; 
            width:100%
        }
        .photo{
            height:200px; 
            width:200px; 
            border-radius:50%; 
            border: 10px solid white;
            position: relative;
            top: -90px;
        }
        .line{
            word-spacing:10px;
            line-height:70px;
        }
        .a{
            display: inline;
        }
        .rg{
            background:rgba(0, 0, 0, 0.8);  
            height:70px; 
            text-align:center;
        }
        .buton{
            background: blue;
            border-radius:25px; 
            width:100%;
        }
        .smal{
            text-align: left;
            margin-left: 50px;
        }
        .publish{
            border-radius:25px;
            width:100%;
            position: relative;            
        }
        .len{
            width:100%;
            position: relative;
            top:0px;
        }
        .play{
            display: none !important;
        }
        .playbt{
            display: none !important;
        }
        @media screen and (max-width:700px){
            .a{
                display: none !important;
            }
            .rg{
                background:transparent;
            }
            .buton{
                background:transparent;
            } 
            .smal{
                text-align: center;
                margin-left: 0px;
            }
            .publish{
                width:50%;
                top:-40px;
                float: right;
            }
            .len{
                width:70%;
                top:-60px;
                float: right;
                margin-right:10px;
            }
            .play{
                display: inline !important;
                margin-left: 100px;
                word-spacing: 15px;
            }
            .playbt{
                display: inline !important;
                margin-left: 20%;
                border-radius: 25px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                   <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
                    <img src="{% static 'images/friendzone2.png' %}" alt="" class="logo">
                    <a href="" class="navbar-brand">FriendZone</a>
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#mynav">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div id="mynav" class="collapse navbar-collapse">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item"><a href="{% url 'project:dash' %}" class="nav-link">Home</a></li>
                            <li class="nav-item"><a href="{% url 'project:find_friend' %}" class="nav-link">FindFriends</a></li>
                            <li class="nav-item"><a href="" class="nav-link"><i class="fas fa-user-friends"></i></a></li>
                            <li class="nav-item"><a href="" class="nav-link"><i class="far fa-comments"></i></a></li>                            
                            <li class="nav-item"><a href="" class="nav-link"><i class="fas fa-bell"></i></a></li>
                            <li class="nav-item"><a href="{% url 'project:basic' %}" class="nav-link"><i class="fas fa-user-cog"></i></a></li>
                            <li class="nav-item"><a href="{% url 'project:logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i></a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row back" >
            <div class="col-md-12 rg" >
                <div class="row">
                    <div class="col-md-3">
                        <img src="/media/{{profile.profile_pic}}" class="photo">
                    </div>
                    <div class="col-md-4 line">
                        <a href="{% url 'project:time' %}" style="color:white;" class="a">Timeline</a>
                        <a href="{% url 'project:abo' %}" style="color:blue;" class="a">About</a>
                        <a href="{% url 'project:alb' %}" style="color:white;" class="a">Album</a>
                        <a href="" style="color:white;" class="a">Friends</a>
                    </div>
                    <div class="col-md-3">
                        <p style="color:white;line-height: 70px; margin-left: 50px;" class="a">1,299 people following her</p>
                    </div>
                    <div class="col-md-2" style="line-height: 70px;">
                        <button class="btn btn-primary text-white m-0 a"><h6>Add Friend</h6></button>                        
                    </div>                  
                </div>
            </div>

            <!-- copied -->

            <div class="col-sm-12 col-12 small" style="display:none">
                <img src="/media/{{profile.profile_pic}}" class="photo">                
            </div>

            <!-- end -->

        </div>
        <div class="row">
            <div class="col-md-12">
                &nbsp;
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4 class="text-primary smal">{{user.first_name}} {{user.last_name}}</h4>
                <p class="text-muted smal">Creative Director</p>
                <div class="play">
                    <a href="{% url 'project:time' %}" style="color:black;" >Timeline</a>
                    <a href="{% url 'project:abo' %}" style="color:blue;" >About</a>
                    <a href="{% url 'project:alb' %}" style="color:black;" >Album</a>
                    <a href="{% url 'project:friends' %}" style="color:black;" >Friends</a>
                </div>
                <div style="line-height: 70px;" class="playbt">
                    <button class="btn btn-primary text-white mb-5 mt-3 playbt"><h6>Add Friend</h6></button>                        
                </div> 
            </div>
            <div class="col-md-7">
                <i class="fas fa-info-circle m-2 text-info" style="font-size:20px"></i><span class="text-muted m-2" style="font-size:20px">My Education</span> <br><br>
                <p class="text-muted">Hello Everyone!! I am {{user.first_name}} {{user.last_name}}.I live in Ludhiana.I am graduated from Guru Nanak Dev University,Jalandhar.</p>
                <hr>
                <div class="row">
                    <div class="col-md-12">
                        <i class="fas fa-briefcase m-2 text-info"></i><span class="text-muted m-2">Work Experiences</span> </a><hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <img src="{% static 'images/sachtech.png' %}" alt="" style="border-radius:100px;height:100px;width:100px">
                    </div>
                    <div class="col-md-10">
                        <p class="text-info mt-2">Sachtech Solution</p>
                        <p class="text-muted">Company Manager - 1 February 2010 to 25 January 2013</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <img src="{% static 'images/wipro.jpg' %}" alt="" style="border-radius:100px;height:100px;width:100px">
                    </div>
                    <div class="col-md-10">
                        <p class="text-info mt-2">Wipro Pvt Ltd</p>
                        <p class="text-muted">Software Developer - 1 February 2013 to 31 December 2016</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <img src="{% static 'images/tcs.png' %}" alt="" style="border-radius:100px;height:100px;width:100px">
                    </div>
                    <div class="col-md-10">
                        <p class="text-info mt-2">Tata Company Services</p>
                        <p class="text-muted">Company Manager - 1 January 2017 to present</p>
                    </div>
                </div><hr>
                <div class="row">
                    <div class="col-md-12">
                        <i class="far fa-comment text-info m-2" style="font-size:20px"><span style="font-size:20px" class="text-muted m-2">Languages</span></i>
                    </div>
                    <ul style="color:rgb(61, 176, 221)">
                        <li>Russian</li>
                        <li>Punjabi</li>
                        <li>Hindi</li>
                        <li>English</li>
                    </ul>
                </div> 
            </div>
            <div class="col-md-2" >
                <p class="text-muted" >{{user.first_name}} {{user.last_name}} Activity</p>
                {% for i in act %}
                <!-- <p class="text-muted mb-1" style="border-left:2px solid green;"><a href="" class="text-primary" >{{i.user.user.first_name}}</a></p> -->
                <p class="text-muted" style="border-left:2px solid green;">{{i.content}}</p>
                <p class="text-muted">{{i.time}}</p>
                <hr/>
                {% endfor %}
            </div> 
        </div>
    </div>
    <hr style="background:linear-gradient(lightblue,skyblue); height:10px; border-radius: 50%;"/>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3">
                    <a href=""><img src="{% static 'images/friendzone2.png' %}" class="logo" />
                        <span class="text-muted" style="font-weight:bold; font-size:30px;">FriendZone</span>
                    </a>
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                    <p class="text-primary">For individuals</p>
                    <ul>
                        <li><a href="" class="text-muted">Sign Up</a></li>
                        <li><a href="" class="text-muted">Login</a></li>
                        <li><a href="" class="text-muted">Explore</a></li>
                        <li><a href="" class="text-muted">Finder app</a></li>
                        <li><a href="" class="text-muted">Features</a></li>
                        <li><a href="" class="text-muted">Language Setting</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                    <p class="text-primary">For businesses</p>
                    <ul>
                        <li><a href="" class="text-muted">Business signup</a></li>
                        <li><a href="" class="text-muted">Business login</a></li>
                        <li><a href="" class="text-muted">Benefits</a></li>
                        <li><a href="" class="text-muted">Resources</a></li>
                        <li><a href="" class="text-muted">Advertise</a></li>
                        <li><a href="" class="text-muted">Setup</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                    <p class="text-primary">About</p>
                    <ul>
                        <li><a href="" class="text-muted">About us</a></li>
                        <li><a href="" class="text-muted">Contact us</a></li>
                        <li><a href="" class="text-muted">Privacy Policy</a></li>
                        <li><a href="" class="text-muted">Terms</a></li>
                        <li><a href="" class="text-muted">Help</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3 mt-3">
                    <p class="text-primary">Contact Us</p>
                    <p>#C-86, Industrial Area, phase-7 Mohali, India</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

templates/settings_interests.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit| Interest</title>
    <link rel="shortcut icon" href="{% static 'images/friendzone2.png' %}">
    <script src="{% static 'jquery.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" >
    <style>
        .logo{
            border-radius:50%; 
            height:30px; 
            font-size: 25px;
        }
        .back{
            background: url("/media/{{profile.cover_pic}}");
            height:400px; 
            padding-top: 300px; 
            background-size:cover; 
            width:100%
        }
        .photo{
            height:200px; 
            width:200px; 
            border-radius:50%; 
            border: 10px solid white;
            position: relative;
            top: -90px;
        }
        .line{
            word-spacing:10px;
            line-height:70px;
        }
        .sidebar-circle{
            height:20px;
            width:20px;
            background:lightgreen;
            border-radius:50%; 
            margin:0 auto; 
            margin-top: 50px;
        }
        .sidebar-line{
            height:930px;
            width:2px;
            background:lightgreen;margin:0 auto
        }
        .a{
            display: inline;
        }
        .rg{
            background:rgba(0, 0, 0, 0.8);  
            height:70px; 
            text-align:center;
        }
        .buton{
            background: blue;
            border-radius:25px; 
            width:100%;
        }
        .smal{
            text-align: left;
            margin-left: 50px;
        }
        .publish{
            border-radius:25px;
            width:100%;
            position: relative;            
        }
        .len{
            width:100%;
            position: relative;
            top:0px;
        }
        .play{
            display: none !important;
        }
        .playbt{
            display: none !important;
        }
        @media screen and (max-width:700px){
            .sidebar-circle{
                background:red;
                display:none !important;
            }
            .a{
                display: none !important;
            }
            .sidebar-line{
            display:none !important;
            }
            .rg{
                background:transparent;
            }
            .buton{
                background:transparent;
            } 
            .smal{
                text-align: center;
                margin-left: 0px;
            }
            .publish{
                width:50%;
                top:-40px;
                float: right;
            }
            .len{
                width:70%;
                top:-60px;
                float: right;
                margin-right:10px;
            }
            .play{
                display: inline !important;
                margin-left: 100px;
                word-spacing: 15px;
            }
            .playbt{
                display: inline !important;
                margin-left: 20%;
                border-radius: 25px;
            }
        }
        
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
                        <img src="{% static 'images/friendzone2.png' %}" alt="" class="logo">
                        <a href="" class="navbar-brand">FriendZone</a>
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#mynav">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div id="mynav" class="collapse navbar-collapse">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item"><a href="{% url 'project:dash' %}" class="nav-link">Home</a></li>
                            <li class="nav-item"><a href="{% url 'project:find_friend' %}" class="nav-link">FindFriends</a></li>
                            <li class="nav-item"><a href="" class="nav-link"><i class="fas fa-user-friends"></i></a></li>
                            <li class="nav-item"><a href="" class="nav-link"><i class="far fa-comments"></i></a></li>                            
                            <li class="nav-item"><a href="" class="nav-link"><i class="fas fa-bell"></i></a></li>
                            <li class="nav-item"><a href="{% url 'project:basic' %}" class="nav-link"><i class="fas fa-user-cog"></i></a></li>
                            <li class="nav-item"><a href="{% url 'project:logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i></a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row back">
            <div class="col-md-12 rg" >
                <div class="row">
                    <div class="col-md-3">
                        <img src="/media/{{profile.profile_pic}}" class="photo">
                    </div>
                    <div class="col-md-4 line">
                        <a href="{% url 'project:time' %}" style="color:white;" class="a">Timeline</a>
                        <a href="{% url 'project:abo' %}" style="color:white;" class="a">About</a>
                        <a href="{% url 'project:alb' %}" style="color:white;" class="a">Album</a>
                        <a href="" style="color:white;" class="a">Friends</a>
                    </div>
                    <div class="col-md-3">
                        <p style="color:white;line-height: 70px; margin-left: 50px;" class="a">1,299 people following her</p>
                    </div>
                    <div class="col-md-2" style="line-height: 70px;">
                        <button class="btn btn-primary text-white m-0 a"><h6>Add Friend</h6></button>                        
                    </div>                  
                </div>
            </div>

            <!-- copied -->

            <div class="col-sm-12 col-12 small" style="display:none">
                <img src="/media/{{profile.profile_pic}}" class="photo">                
            </div>

            <!-- end -->

        </div>
        <div class="row">
            <div class="col-md-12">
                &nbsp;
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4 class="text-primary smal">{{user.first_name}} {{user.last_name}}</h4>
                <p class="text-muted smal">Creative Director</p>
                <div class="play">
                    <a href="{% url 'project:time' %}" style="color:blue;" >Timeline</a>
                    <a href="{% url 'project:abo' %}" style="color:black;" >About</a>
                    <a href="{% url 'project:alb' %}" style="color:black;" ">Album</a>
                    <a href="" style="color:black;" >Friends</a>
                </div>
                <div style="line-height: 70px;" class="playbt">
                    <button class="btn btn-primary text-white mb-5 mt-3 playbt"><h6>Add Friend</h6></button>                        
                </div>
                <ul type="none" class="mt-5">
                    <li class="my-2"> <a href="{% url 'project:basic' %}" style="color:black"><i class="fas fa-info-circle m-2"></i><span>Basic Infomation</span></a></li><hr>
                    <li class="my-2"> <a href="{% url 'project:education' %}" style="color:black"><i class="fas fa-briefcase m-2"></i><span>Education and Work</span> </a></li><hr>
                    <li class="my-2" style="border-left:2px solid lightgreen;"> <a href="{% url 'project:interest' %}" style="color:black"><i class="fas fa-heart m-2"></i><span>My Interests</span></a></li><hr>
                    <li class="my-2"> <a href="{% url 'project:account' %}" style="color:black"><i class="fas fa-sliders-h m-2"></i><span>Account Settings</span></a></li><hr>
                    <li class="my-2"> <a href="{% url 'project:password' %}" style="color:black"><i class="fas fa-lock m-2"></i><span>Change Password</span> </a></li><hr>
                </ul>
            </div>
            <div class="col-md-7">
                <i class="fas fa-heart m-2 text-info" style="font-size:20px;"></i><span class="m-2" style="font-size:20px;">My Interests</span> <hr>
                <p class="text-muted">“The beauty and mystery of this world only emerges through affection, attention, interest and compassion . . . open your eyes wide and actually see this world by attending to its colors, details and irony.” </p> <hr>
                <div class="row">
                    <div class="col-md-12">
                        <a href="" class="bg-success p-2  text-white"style="border-radius:20px;"><i class="fas fa-bicycle"></i>&nbsp Bicycle</a>
                        <a href="" class="bg-success p-2 text-white"style="border-radius:20px;"><i class="fas fa-shopping-cart"></i>&nbsp Shopping</a>
                        <a href="" class="bg-success p-2 text-white"style="border-radius:20px;"><i class="fas fa-utensils"></i>&nbsp Food</a>
                        <a href="" class="bg-success p-2 text-white"style="border-radius:20px;"><i class="fas fa-camera"></i>&nbsp Photography</a>
                        <a href="" class="bg-success p-2 text-white"style="border-radius:20px;"><i class="fas fa-plane"></i>&nbsp Travelling</a>
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="text-muted">Add Interests</p>
                    </div>
                    <div class="col-md-8">
                        <div class="form-group">
                            <input type="text" name="" id="" class="text-muted form-control" placeholder="Interests e.g. Photography,Singing">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-primary btn-block">Add</button>
                    </div>
                </div>
            </div>
            <div class="col-md-2" >
                <p class="text-muted" >{{user.first_name}} {{user.last_name}} Activity</p>
                {% for i in act %}
                <!-- <p class="text-muted mb-1" style="border-left:2px solid green;"><a href="" class="text-primary" >{{i.user.user.first_name}}</a></p> -->
                <p class="text-muted" style="border-left:2px solid green;">{{i.content}}</p>
                <p class="text-muted">{{i.time}}</p>
                <hr/>
                {% endfor %}
            </div> 
        </div>
    </div>
    <hr style="background:linear-gradient(lightblue,skyblue); height:10px; border-radius: 50%;"/>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3">
                    <a href=""><img src="{% static 'images/friendzone2.png' %}" class="logo" />
                        <span class="text-muted" style="font-weight:bold; font-size:30px;">FriendZone</span>
                    </a>
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                    <p class="text-primary">For individuals</p>
                    <ul>
                        <li><a href="" class="text-muted">Sign Up</a></li>
                        <li><a href="" class="text-muted">Login</a></li>
                        <li><a href="" class="text-muted">Explore</a></li>
                        <li><a href="" class="text-muted">Finder app</a></li>
                        <li><a href="" class="text-muted">Features</a></li>
                        <li><a href="" class="text-muted">Language Setting</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                    <p class="text-primary">For businesses</p>
                    <ul>
                        <li><a href="" class="text-muted">Business signup</a></li>
                        <li><a href="" class="text-muted">Business login</a></li>
                        <li><a href="" class="text-muted">Benefits</a></li>
                        <li><a href="" class="text-muted">Resources</a></li>
                        <li><a href="" class="text-muted">Advertise</a></li>
                        <li><a href="" class="text-muted">Setup</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                    <p class="text-primary">About</p>
                    <ul>
                        <li><a href="" class="text-muted">About us</a></li>
                        <li><a href="" class="text-muted">Contact us</a></li>
                        <li><a href="" class="text-muted">Privacy Policy</a></li>
                        <li><a href="" class="text-muted">Terms</a></li>
                        <li><a href="" class="text-muted">Help</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3 mt-3">
                    <p class="text-primary">Contact Us</p>
                    <p>#C-86, Industrial Area, phase-7 Mohali, India</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>